server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    username: springuser
    password: ThePassword
    url: jdbc:mysql://localhost:3306/rps_app
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

application:
  tcp: 54555